# Generated by Django 4.1.5 on 2023-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_body_post_content_remove_post_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='certificate',
        ),
        migrations.AddField(
            model_name='post',
            name='certificate',
            field=models.ManyToManyField(to='main.certificate'),
        ),
    ]
