# Generated by Django 4.1.5 on 2023-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_certificate_post_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='certificate',
            field=models.ManyToManyField(related_name='certificates', to='main.certificate'),
        ),
    ]
