# Generated by Django 4.1.5 on 2023-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='certificate',
            field=models.ManyToManyField(null=True, related_name='certificates', to='main.certificate'),
        ),
    ]
