# Generated by Django 4.1.5 on 2023-03-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_applycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycontent',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
